Repository djesusguimaraes/proj-sist-2021-2, pull requests merged in 2021-12, with the labels that each got.

#21 Feature | R11 | T03 | Escolha de Mapa
  lib/app/global/models/entities/delivery_at.dart
  lib/app/global/models/entities/product.dart
  lib/app/global/repositories/client_address/client_address_repository.dart
  lib/app/modules/client_address/client_address_page.dart
  lib/app/modules/client_address/client_address_store.dart
  lib/app/modules/client_address/pages/saved_addresses.dart
  lib/app/modules/client_address/pages/search_address.dart
  lib/app/modules/register_client/register_client_repository.dart
  lib/app/modules/restaurant/restaurant_page.dart
  lib/app/modules/restaurant/restaurant_service.dart
  lib/app/modules/restaurant/restaurant_service_firestore.dart
  lib/app/modules/restaurant/restaurant_store.dart
  lib/app/modules/restaurant/restaurant_store.g.dart
  lib/app/modules/restaurant/widgets/product_options/product_dialog.dart
  lib/app/modules/restaurant/widgets/restaurant_top_bar.dart
  lib/app/modules/restaurant_home/components/update_profile/components_profile_dialog.dart
  pubspec.lock
Labels: bug, RW, R11

#20 Feature/rw02/t05/refatoracao do pop up
  lib/app/modules/restaurant/widgets/product_options/product_dialog.dart
Labels: RW

#22 Feature/ r11 / t02 / busca lista endereco (em lista)
  lib/app/global/models/entities/delivery_at.dart
  lib/app/global/models/enums/address_type.dart
  lib/app/modules/client_address/client_address_store.dart
  lib/app/modules/client_address/pages/search_address.dart
  lib/app/modules/client_address/widgets/address_list_tile.dart
  lib/app/modules/client_address/widgets/search_textfield.dart
Labels: R11

#23 Feature/r11/t01/tela enderecos salvos
  lib/app/modules/client_address/client_address_module.dart
  lib/app/modules/restaurant/widgets/restaurant_top_bar.dart
  pubspec.lock
  pubspec.yaml
Labels: RW
